### PR TITLE
chore: delete vscode settings

### PR DESCRIPTION
**Pull request by craicoverflow**

### CODE REVIEW

**Comment by wtrocki** [comment]
What happened to codereviews? I use that every day. Why deleting?

**Comment by wtrocki** [comment]
Maybe better to add that to gitignore. I can have my custom settings etc.

**Comment by craicoverflow** [comment]
> I use that every day. Why deleting?

What were you using it for?

**Comment by wtrocki** [comment]
So I have custom settings for plugings, overriding linter so I can see lint errors in editor etc. 
Anyway.. I will will that in my PR :)

**Comment by craicoverflow** [comment]
I added this originally. Realistically though everyone would have their own editor settings. I did not PR as I am mainly needing to merge to main to test midstream CI, and did not think this one was worth a review. Sorry.

**Comment by wtrocki** [comment]
Ok. 
https://github.com/redhat-developer/app-services-cli/pull/883

**Pull request merged**
