### PR TITLE
fix: cannot delete service registry by name

### PR DESCRIPTION
**Pull request by wtrocki**
Fixes: https://github.com/redhat-developer/app-services-cli/issues/785

### CODE REVIEW

**Comment by wtrocki** [comment]
@craicoverflow this fixes broken documentation on master and also minor bug in registry delete.

**Review by craicoverflow — CHANGES_REQUESTED** [review]
Does not work when passing the name as a flag:

```shell
❯ ./rhoas service-registry delete registry1 -y
Deleting "registry1" Service Registry instance.

Error: 405 Method Not Allowed
```

You need to change line 117.

**Comment by wtrocki** [comment]
I have tested that before and now:

```
[wtrocki@graphapi app-services-cli (main ✗)]$ rhoas service-registry create test
Creating Service Registry with name: test
Successfully created Service Registry
{
  "href": "",
  "id": "121",
  "name": "test",
  "owner": "Unauthenticated",
  "registryUrl": "",
  "status": "PROVISIONING"
}
[wtrocki@graphapi app-services-cli (main ✗)]$ rhoas service-registry delete test -y
Deleting "test" Service Registry instance.

Service Registry instance "test" was deleted.
```

**Comment by wtrocki** [comment]
Rebased. Ready for review

**Comment by rkpattnaik780** [comment]
Not able to test it in either mock or staging, is it expected?
Screenshot from 2021-07-02 17-22-53

**Comment by rkpattnaik780** [comment]
Pasting the debug log:

Screenshot from 2021-07-02 17-34-10

**Comment by wtrocki** [comment]
@rkpattnaik780 sadly enough backend folks broken entire CLI

**Comment by wtrocki** [comment]
Backend we have provisioned is broken but running it locally with date fix works. Merged as there are multiple fixed that I needed in follow up PRs

**Pull request merged**
