### PR TITLE
feat(service-registry rule): add disable and and update command

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Disable and update command for service-registry rules.

### Verification Steps

1. Run the following command to update config value of an enabled rule:
```
rhoas service-registry rule update --rule-type compatibility --config forward 
```
2. Run the following command to disable all global rules.
```
rhoas service-registry rule disable 
```

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [X] Documentation added for the feature
- [X] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
> Me thinking: can disable be just flag as part of the update? Does this make your life easier? If not ignore

I will prefer having a separate disable command.

**Comment by rkpattnaik780** [comment]
@wtrocki I wanted update to have interactive mode too, for suggesting valid config values. The problem is that unlike `enable`, update needs to check if a rule exists (is already enabled) , for which we will need values of `registry-instance ID`, `group` and `artifact-id` beforehand.

**Comment by wtrocki** [comment]
verifying now

**Comment by wtrocki** [comment]
@rkpattnaik780 I see some strange behaviour where text with progress disappears 

> Disabling rule.. 

and then it is gone in second

**Review by wtrocki — APPROVED** [review]
Verified *all* commands:

- Global rules
- rules for artifact. 

Made incompatible changes with rule applied and artifact update was rejected.

**Pull request merged**
