### PR TITLE
feat: merged kafka i18n messages into a single file

### LINKED ISSUE #757: Merge kafka crud i18n into single file
## Description

Currently navigation between multiple files/common elements is very hard. 

We should have developer UX oriented i18n (not file oriented that causes a lot of confusion and has number of entries duplicated). Without using single file we cannot detect duplicates which are currently in main branch.

## Proposed files
```
kafka_crud.en.toml
registry_crud.en.toml
serviceaccount_crud.en.toml
cluster_en.toml
kafka_consumer_group.en.toml
kafka_topics.en.toml
```

### PR DESCRIPTION
**Pull request by alexal**
Closes #757

### CODE REVIEW

**Comment by alexal** [comment]
@wtrocki have you had a chance to review the changes?

**Review by wtrocki — APPROVED** [review]
Reviewed changes. Verified.

**Comment by wtrocki** [comment]
Sadly rebase is needed.

**Comment by alexal** [comment]
@wtrocki ,

> Sadly rebase is needed.

I brought your yesterday's changes. Please review.

**Comment by wtrocki** [comment]
Still conflicts

**Comment by wtrocki** [comment]
Some of my Commits got into this. I can help you with rebase but would need to close this PR and open new one :)

**Comment by alexal** [comment]
> Some of my Commits got into this. I can help you with rebase but would need to close this PR and open new one :)

Yes, looks like I messed it up.

**Comment by alexal** [comment]
I will create a new one, please close this.

**Comment by alexal** [comment]
Here is a new one #997 997

**Pull request closed without merging**
