### PR TITLE
feat(artifact list): add flags to filter result

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Added `--name`, `--labels`, `--description` and `--properties` flag to `service-registry artifact list` command to enable filtering the artifacts.

### Verification Steps
Run the following commands by adjusting the parameters in accordance to the artifact list:
```
## List all artifacts for the "default" artifact group with name containing "sample"
rhoas service-registry artifact list --name sample

## List all artifacts for the "default" artifact group having label "my-label"
rhoas service-registry artifact list --label "my-label"

## List all artifacts for the "default" artifact group with description containing "sample"
rhoas service-registry artifact list --description sample
```

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [X] Documentation added for the feature
- [X] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
Not able to verify `--property` flag, unsure what `property` here actually refers to in the artifact.

**Comment by wtrocki** [comment]
@jsenko do you know what property does?

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
Properties can be edit and changed as in the docs:
https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/getting-started/assembly-registry-reference.html#registry-artifact-metadata_registry

After doing search with property all seems to work fine. Amazing job!

**Comment by rkpattnaik780** [comment]
> Properties can be changed as in the docs: https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/getting-started/assembly-registry-reference.html#registry-artifact-metadata_registry
> 
> After doing search with property all seems to work fine. Amazing job!

I am probably doing it wrong, Can you paste the command here so I can try myself and put it in example docs.

**Comment by wtrocki** [comment]
Not on laptop right now but steps are as follows

1. We need to edit metadata first

rhoas service-registry artifact metadata-edit

In editor add property and close it
Then we  can get metadata cmd to see it.

**Comment by rkpattnaik780** [comment]
> Not on laptop right now but steps are as follows
> 
> 1. We need to edit metadata first
> 
> rhoas service-registry artifact metadata-edit
> 
> 2. In editor add property and close it
>    Then we  can get metadata cmd to see it.
> 
> 3.Use property filter

Doesn't work for me.

Screenshot from 2021-12-20 13-36-38

**Comment by wtrocki** [comment]
You are right! I created issue to discus problem with team: https://github.com/Apicurio/apicurio-registry/issues/2125
I think we can merge that PR despite that problem as it is not related to the CLI itself

**Pull request merged**
