### PR TITLE
refactor: use make to create fixed size list

### LINKED ISSUE #911: Change artifactrows in list commands
```suggestion
	var rows []artifactRow
```

This will create the same value - in Go it is generally preferred to create variables which have not been given a value using `var`.

As an aside, this slice does not have a fixed value - but since we know what the size will be we could set a fixed size.

See https://github.com/redhat-developer/app-services-cli/blob/reset_offset/pkg/cmd/kafka/consumergroup/resetoffset/reset_offset.go#L241

This will have no noticeable impact on performance for the CLI, so i's totally optional, just letting you know that it is possible.

_Originally posted by @craicoverflow in https://github.com/redhat-developer/app-services-cli/pull/859#discussion_r687897771_

### PR DESCRIPTION
**Pull request by alexal**
Closes #911 

**Verification Steps**

- [ ] Run export RHOAS_DEV=true to enable this hidden feature.
- [ ] Create a Service Registry instance, or skip this if you already have one.
- [ ] Run rhoas `service-registry artifact list` it should provide list of Service Registry artifacts

Type of change

- [ ] Other: code refactoring

### CODE REVIEW

**Comment by craicoverflow** [comment]
This is a `refactor`.

**Comment by craicoverflow** [comment]
@alexal can you please provide verification steps with every pull request?

**Comment by alexal** [comment]
> @alexal can you please provide verification steps with every pull request?

Like what command to run to make sure it works?

**Comment by craicoverflow** [comment]
Yes, most pull requests should have one. Here's an example: https://github.com/redhat-developer/app-services-cli/pull/1050

**Comment by alexal** [comment]
> Yes, most pull requests should have one. Here's an example: #1050

Sure, not a problem.

**Review by craicoverflow — APPROVED** [review]

**Pull request merged**
