### PR TITLE
feat: added a custom user-agent

### LINKED ISSUE #994: Cli should use custom user agent when making requests to all SDK
## Description

See Connection structure that does define all APIs. 

When building API objects we need to override User-Agent with RHOAS CLI name and it's version.

### PR DESCRIPTION
**Pull request by alexal**
Closes #994

### CODE REVIEW

**Comment by wtrocki** [comment]
Hi

Thank you so much for your contribution. Sadly linting errors are present

**Comment by alexal** [comment]
@wtrocki ,

> Thank you so much for your contribution. Sadly linting errors are present

I've fixed lint errors, however the build is still failing. Any ideas why?

**Comment by craicoverflow** [comment]
You need to run `make docs/generate` to generate documentation.

**Comment by alexal** [comment]
> You need to run `make docs/generate` to generate documentation.

I did that already, however, nothing was updated.

❯ make docs/generate
rm -rf ./docs/commands/*
GENERATE_DOCS=true RHOAS_DEV=false go run ./cmd/rhoas

🛠️  Generating rhoas command-line reference documentation...

✅ Command-line reference documentation has been generated successfully
❯ git status
On branch feat/994
Your branch is up to date with 'origin/feat/994'.

nothing to commit, working tree clean

**Comment by alexal** [comment]
Please close this one, I will create a new one PR as my commits were messed up again.

**Comment by alexal** [comment]
This is a new PR #1006

**Pull request closed without merging**
