### PR TITLE
Support for schema building

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by jackdelahunt** [comment]
Wasn't able to get this to work always just 'Additional properties not supported yet' for any connector type I enter

**Comment by wtrocki** [comment]
I forgot to bump the version of the library here: https://github.com/wtrocki/survey-json-schema/releases/tag/v0.5.0

**Comment by jackdelahunt** [comment]
Found an issue with picking AWS region.

- Run `rhoas connector build --type=aws_kinesis_sink_0.1`
- Get to picking AWS region and I get the following error for every option I pick
   - ```Sorry, your reply was invalid: {ap-northeast-1 2} not found in [af-south-1 ap-east-1 ap-northeast-1 ap-northeast-2 ap-northeast-3 ap-south-1 ap-southeast-1 ap-southeast-2 ap-southeast-3 ca-central-1 eu-central-1 eu-north-1 eu-south-1 eu-west-1 eu-west-2 eu-west-3 fips-us-east-1 fips-us-east-2 fips-us-west-1 fips-us-west-2 me-south-1 sa-east-1 us-east-1 us-east-2 us-west-1 us-west-2 cn-north-1 cn-northwest-1 us-gov-east-1 us-gov-west-1 us-iso-east-1 us-iso-west-1 us-isob-east-1] ```

**Comment by wtrocki** [comment]
Thank you so much. I will actually download all connectors schemas and test them

**Comment by jackdelahunt** [comment]
Passing a empty type `rhoas connector build --type=` gives this error and not something like type needs to be set.

```
Creating connector specification
❌ Unable to find root element in &{[] map[] true}. Run the command in verbose mode using the -v flag to see more information
```

**Comment by wtrocki** [comment]
> Passing a empty type rhoas connector build --type= gives this error and not something like type needs to be set.

Nice! Same happens for `rhoas connector type describe `

**Comment by jackdelahunt** [comment]
Current build is not working:

- Run `make binary`
- Run `./rhoas`
- Got `expected value for key "error" be a string but got map[string]interface {}{"one":"cannot read file content"}`

**Comment by jackdelahunt** [comment]
Running `rhoas connector build --type=data_generator_0.1 --output-file=spec.json` over and over does not overwrite file it appends to it

**Comment by wtrocki** [comment]
> Appends

Yes. I have that fixed along with number of other bugs.

**Comment by wtrocki** [comment]
@jackdelahunt do you mind taking look on this.  I removed json schema based interactive mode and I think we need to build one manually.

**Pull request merged**
