### PR TITLE
Connect namespace bugfix

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by craicoverflow** [comment]
Verification steps?

**Comment by wtrocki** [comment]
This can be verified with minikube and headless operator (just CRDs)

See instruction: https://github.com/redhat-developer/app-services-operator/pull/289

**Comment by craicoverflow** [comment]
> This can be verified with minikube and headless operator (just CRDs)
> 
> See instruction: [redhat-developer/app-services-operator#289](https://github.com/redhat-developer/app-services-operator/pull/289)

```shell
$ cd olm/olm-catalog/rhoas-operator/0.9.0/manifests
kubectl apply -f .
customresourcedefinition.apiextensions.k8s.io/cloudserviceaccountrequests.rhoas.redhat.com created
customresourcedefinition.apiextensions.k8s.io/cloudservicesrequests.rhoas.redhat.com created
customresourcedefinition.apiextensions.k8s.io/kafkaconnections.rhoas.redhat.com created
customresourcedefinition.apiextensions.k8s.io/serviceregistryconnections.rhoas.redhat.com created
clusterrole.rbac.authorization.k8s.io/kafkaconnections-sbo-view created
error: unable to recognize "rhoas-operator.clusterserviceversion.yaml": no matches for kind "ClusterServiceVersion" in version "operators.coreos.com/v1alpha1"
```

**Comment by wtrocki** [comment]
@craicoverflow that is ok. you can ignore that issue

**Comment by craicoverflow** [comment]
Since I had already started it I wanted to see it out. I installed operator framework and olm on minikube, then install the service-bind operator and things started to work. 
We should try to have some at least some verification steps in non-trivial PRs that help guide the reviewer and also explain the expected outcome to verification (something that the linked script does not show). It will save so much time.

Anyway, I got this far:

```shell
**❯ ./rhoas cluster connect --token $TOKEN --namespace development
? Select type of service kafka
This command will link your cluster with Cloud Services by creating custom resources and secrets.
In case of problems please execute "rhoas cluster status" to check if your cluster is properly configured

Connection Details:

Service Type:                   kafka
Service Name:                   enda-dev
Kubernetes Namespace:           development
Service Account Secret:         rh-cloud-services-service-account

? Do you want to continue? Yes
✔️  Token Secret "rh-cloud-services-accesstoken" created successfully
✔️  Service Account Secret "rh-cloud-services-service-account" created successfully

Client ID:     srvc-acct-159ed9b6-9d69-4ce3-8fa2-68a72d4132a7

Make a copy of the client ID to store in a safe place. Credentials won't appear again after closing the terminal.

You will need to assign permissions to service account in order to use it. 
For example for Kafka service you should execute the following command to grant access to the service account:

  $ rhoas kafka acl grant-access --producer --consumer --service-account srvc-acct-159ed9b6-9d69-4ce3-8fa2-68a72d4132a7 --topic all --group all

✔️  kafka resource "enda-dev" has been created
Waiting for status from kafka resource.
Created kafka can be already injected to your application.

To bind you need to have Service Binding Operator installed:
https://github.com/redhat-developer/service-binding-operator

You can bind kafka to your application by executing "rhoas cluster bind" 
or directly in the OpenShift Console topology view.

❌ Process of watching kafka timed out. Run the command in verbose mode using the -v flag to see more information
```

I'm not sure if this is valid or not.

**Comment by wtrocki** [comment]
>  I installed operator framework and olm on minikube, then install the service-bind operator and things started to work.

That wasn't needed, but it is good that you have tried it. We need to work with @secondsun on improving this workflow.
We have running openshift cluster right now that has all of that installed as well.

> We should try to have some at least some verification steps in non-trivial PRs that help guide the reviewer 

Verification steps for rhoas cluster connect would be to always have OpenShift cluster with 2 operators installed. 
I wanted to try out kubernetes path and it works but as you have noticed it is not refined/documented yet.

> I'm not sure if this is valid or not.

Yes. That is ok as we do not have operator running.

**Comment by wtrocki** [comment]
@craicoverflow I have verified this end to end so no worries this works fine. Problem was that we were picking current namespace in the helper methods (which happened to be used only in single place).

**Comment by wtrocki** [comment]
As for cluster connect I think that having our CLI requiring operator/openshift is not good practice so overall we will be moving out of that flow towards what I have described in https://github.com/redhat-developer/app-services-cli/issues/1306

**Comment by wtrocki** [comment]
@rkpattnaik780 Just for review (@craicoverflow have verified it)

**Review by rkpattnaik780 — APPROVED** [review]

**Pull request merged**
