### PR TITLE
fix(completion): fix dynamic completions for Bash

### LINKED ISSUE #554: Auto-completion not working for positional arguments with bash
## Description

**Version**: 0.21.0

### Steps to reproduce

1. Enable completion for Bash.
2. After logging in, select a kafka nstance with `./rhoas kafka use`.
3. Try to run `describe` command, instead of typing the name of entire topic, press tab(which should trigger auto-completion).

### Expected vs actual behaviour

Bash will display list of directories in the current directory when a list of topics should've been displayed.

Screenshot from 2021-04-09 14-47-09

### PR DESCRIPTION
**Pull request by craicoverflow**
Closes #554 

### Verification Steps

1. Re-install the Bash completion scripts for good measure.
2. Ensure you are in a Bash shell.
3. Run `rhoas kafka topic describe <TAB>` to let the dynamic auto completion function show the list of topics available.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist

- [x] Documentation added for the feature
- [x] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by craicoverflow** [comment]
I believe this should work now @rkpattnaik780

**Review by rkpattnaik780 — COMMENTED** [review]
The issue with auto-suggestion in zsh seems to be fixed, however the issue with bash still persists. Also noticing an inconsistent behavior, `kafka use` shows list of kafkas for auto-suggestions in zsh whereas bash populates it with `--id=` flag.

**Comment by wtrocki** [comment]
@rkpattnaik780 What versions of bash and zsh you have. Do you use oh my zsh or plan zsh?

**Comment by rkpattnaik780** [comment]
> @rkpattnaik780 What versions of bash and zsh you have. Do you use oh my zsh or plan zsh?

Yes I do use zsh.

Bash: 5.0.17
Zsh: 5.8

**Comment by craicoverflow** [comment]
@wtrocki do dynamic completions work okay for you using Bash?

**Comment by wtrocki** [comment]
Doesn't seem to be working at all on bash 5.1 (but 5.x seems to be working for @rkpattnaik780)
They work on latest zsh just fine.
```
bash-5.1$ rhoas
.localized    Shared/       wojtektrocki/ wtrocki/
```

**Comment by craicoverflow** [comment]
> The issue with auto-suggestion in zsh seems to be fixed, however the issue with bash still persists. Also noticing an inconsistent behavior, `kafka use` shows list of kafkas for auto-suggestions in zsh whereas bash populates it with `--id=` flag.

That is most strange.. @wtrocki just confirmed that this does not happen for him with Bash 5, nor for me!

**Comment by wtrocki** [comment]
I would simply document it as limitations. ZSH seems to be standard now for Mac (and used a lot in Linux as well)

**Comment by craicoverflow** [comment]
Going to merge this, as it works fine for two of us. We can try and revisit it again but it is lower priority for now.

**Pull request merged**
