### PR TITLE
Service Registry CLI help text edits

### PR DESCRIPTION
**Pull request by smccarthy-ie**
Copy edits to the CLI help text for the new service-registry instance and artifact commands 

### Verification Steps
Run the rhoas service-registry command help

### Type of change
- [x ] Documentation change

### Checklist
- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by wtrocki** [comment]
@smccarthy-ie Amazing work! Thank you so much for checking this. I'm still adding commands so will ping you now on every new PR for consistency.

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
World class job! Thank you so much.

To merge your changes you should run `make docs/generate` on your machine and push documentation changes.
I can do that for you in case of issues.

**Comment by smccarthy-ie** [comment]
Hi @wtrocki This one is for copy edits and tidy up to the CLI help text only. 

I noticed there is no `.adoc` output for the new Service Registry commands. I think these were deliberately disabled previously to avoid publishing docs before the feature was released? 

Can you re-enable and regenerate the docs when you get a chance (i.e., for release with the SR public eval on Sept 24)?

When I tried to regenerate the docs, I got an error: 
```$ make docs/generate
rm -rf ./docs/commands/*
GENERATE_DOCS=true RHOAS_DEV=false go run ./cmd/rhoas
build github.com/redhat-developer/app-services-cli/cmd/rhoas: cannot load embed: malformed module path "embed": missing dot in first path element
make: *** [docs/generate] Error 1```
 
 Thanks!

**Comment by wtrocki** [comment]
It will do docs update for you. 

> Can you re-enable and regenerate the docs when you get a chance (i.e., for release with the SR public eval on Sept 24)?

I wasn't aware of that deadline. This will mean we should make service registry commands public (not available in dev mode like now). Provide updates to RHAOS CLI guide to include service registry etc. 

CC @paoloantinori should we enable that for Sept 24? We still missing some commands

**Comment by craicoverflow** [comment]
Regarding:

> build github.com/redhat-developer/app-services-cli/cmd/rhoas: cannot load embed: malformed module path "embed": missing dot in first path element

I think this is because you do not have go 1.16 installed?

**Comment by wtrocki** [comment]
@smccarthy-ie Upgrading go and running it again will be good - I cannot push to your fork for some reason.

**Comment by smccarthy-ie** [comment]
@wtrocki @craicoverflow 
Yes I had an earlier version of Go installed on my laptop. yum upgrade only gets me as far as go1.15.14, which also gives errors. When I download and install go 1.16 using https://golang.org/doc/install, the go version is still 1.15. 

Can you incorporate these text edits in your next PR to help unblock this issue? Thanks!

**Comment by craicoverflow** [comment]
I use Go Version Manager, its very handy: https://github.com/moovweb/gvm

Did you uninstall Go first? You probably have 2 on your system.

**Comment by wtrocki** [comment]
Closing to open new PR

**Pull request closed without merging**
