### PR TITLE
Minor adjustments to command ref layout

### PR DESCRIPTION
**Pull request by bhardesty**
<!-- Add a description here or link to the relevant GitHub issue>
For the CLI command ref: change "See Also" to sentence case, adjust heading levels, and add "[discrete]" markup to each section.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by bhardesty** [comment]
For the command ref, change "See Also" to sentence case, adjust heading levels, and add "[discrete]" to each section.

**Comment by wtrocki** [comment]
@bhardesty 

`make docs/generate-modular-docs` and `make docs/generate` will generate new docs for resting

**Review by pmuir — APPROVED** [review]

**Comment by wtrocki** [comment]
Will do that for you @bhardesty

**Comment by wtrocki** [comment]
Ok. Time to rebase other PR :D

**Comment by bhardesty** [comment]
> @bhardesty Awesome contribution. Thank you so much

No problem, and thanks for the tip about building the docs. I did run "make test", but it didn't find any changes to test :-).

**Pull request merged**
