### PR TITLE
Renames for service account and consumer group commands

### PR DESCRIPTION
**Pull request by wtrocki**
Use hyphenated names for all multiword commands.
This effort will help us to standarize format for all commands we have.
This is breaking change but it will be delivered with breaking backend change so everyone will be advised to update CLI.

Docs were updated:
https://github.com/redhat-developer/app-services-guides/pull/191/files
Fixes
https://github.com/redhat-developer/app-services-cli/issues/774

### CODE REVIEW

**Review by craicoverflow — CHANGES_REQUESTED** [review]
i18n files need to be updated. All good otherwise

**Comment by wtrocki** [comment]
> i18n files need to be updated

Which ones? The only ones were the top level ones

**Comment by craicoverflow** [comment]
> > i18n files need to be updated
> 
> Which ones? The only ones were the top level ones

Nope. There are lots of `examples` defined.

**Comment by wtrocki** [comment]
Yes.. Looking at this now.

**Comment by rkpattnaik780** [comment]
Global search shows few things still need to be changed in toml files

**Comment by wtrocki** [comment]
Done changes in examples

**Review by rkpattnaik780 — APPROVED** [review]

**Pull request merged**
