### PR TITLE
refactor: split `pkg` to shared, cmd and core

### PR DESCRIPTION
**Pull request by rkpattnaik780**
`pkg` has been split into:
* `core` - elements independent of service
* `shared` - common code assuming existence of all services.
* `cmd` - Commands along with their helpers

### Current directory structure
|─ pkg
|── cmd
|   ├── kafka
|   ├── registry
|   ├── serviceaccount
|   ├── cluster
|   ├── .....
|── core
|   ├── cmdutil
|   ├── config
|   ├── errors
|   ├── logging
|   ├── localize
|   ├── ...
|── shared
|   ├── accountmgmtutil
|   ├── cluster
|   ├── connection
|   ├── factory
|   ├── kafkautil
|   ├── remote
|   ├── serviceregistryutil
|   ├── servicespec
|   ├── svcstatus
|   ├── ...

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [X] Refactor

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by craicoverflow** [comment]
> shared - common code assuming existence of all services.

Would we not just assume that everything NOT in core will be shared?

**Comment by rkpattnaik780** [comment]
> > shared - common code assuming existence of all services.
> 
> Would we not just assume that everything NOT in core will be shared?

That will be a better explanation, will change it.

**Comment by rkpattnaik780** [comment]
@craicoverflow , completions will be better suited for `shared` imho, wdyt?

**Comment by wtrocki** [comment]
Reviewed and verified locally! Great job!

**Comment by wtrocki** [comment]
Actually. I still see some circular dependencies:

- pkg/core/config - has kafka and registry - I think we can ignore that for moment
- completions.go references shared folder kafka utils

**Comment by wtrocki** [comment]
https://github.com/redhat-developer/app-services-cli/blob/refactor_2/pkg/core/cmdutil/flagutil/completions.go#L90:L103 

those two can be eather:
- moved to shared
- Move to internal in the cmd.

**Comment by craicoverflow** [comment]
> @craicoverflow , flag completions will be better suited for `shared` imho, wdyt?

Which package is "flag completions"?

**Comment by craicoverflow** [comment]
> Move to internal in the cmd (my prefference)

`flagutil` is actually a base package - flagutil packages for subcommands actually embed this a lot.

**Comment by wtrocki** [comment]
I meant only this two util methods.

**Comment by craicoverflow** [comment]
> I meant only this two util methods.

* `RegisterTopicCompletionFunc` - related to topics - should be in the flagutil for topics as it could be used in multiple commands (delete and update)
* `RegisterGroupCompletionFunc` - relates to consumer groups - should be in consumergroup flag util package.

**Comment by rkpattnaik780** [comment]
> * `RegisterTopicCompletionFunc` - related to topics - should be in the flagutil for topics as it could be used in multiple commands (delete and update)
> * `RegisterGroupCompletionFunc` - relates to consumer groups - should be in consumergroup flag util package.

Since they are used by acls, I think we should keep them at higher level or aclcmdutil.

**Comment by craicoverflow** [comment]
> Since they are used by acls, I think we should keep them at higher level.

If that is the case - agreed. though it should be at the higher level then like `kafkadataflagutil` or something.

> or aclcmdutil

Probably not, because we would want them in the topic and consumer-group commands?

**Comment by rkpattnaik780** [comment]
> Probably not, because we would want them in the topic and consumer-group commands?

Since they are specific to `--topic` and `--group` flag, we can keep it in `aclcmdutil`

**Comment by wtrocki** [comment]
LGTM

**Pull request merged**
