### PR TITLE
fix: remove dev preview

### PR DESCRIPTION
**Pull request by wtrocki**
WIP

### CODE REVIEW

**Comment by wtrocki** [comment]
@smccarthy-ie will finish that tommorow.

**Comment by wtrocki** [comment]
@smccarthy-ie is that ok to be released today?

**Comment by smccarthy-ie** [comment]
> @smccarthy-ie is that ok to be released today?

@wtrocki Thanks, yes ideal to merge this today so we will have time to check content before publication on Dec 1.

**Comment by wtrocki** [comment]
I meant if we ok to release CLI with that help changes today. I guess that is not a issue right?

**Comment by smccarthy-ie** [comment]
OK, thanks. Don't think this is an issue.

**Pull request merged**
